# Generated by Django 4.1.1 on 2022-10-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='tag_for_posts', to='blog.tag'),
        ),
    ]
