# Generated by Django 4.1.1 on 2022-11-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_author_about_author_image_author_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
